# https://hydra.cc/docs/configure_hydra/intro/

# enable color logging
defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog

# output directory, generated dynamically on each run
run:
  dir: ${paths.log_dir}/${tags.0}/${tags.1}/${tags.2}/${tags.3}/${now:%Y-%m-%d}_${now:%H-%M}
sweep:
  dir: ${paths.log_dir}/multiruns/${tags.0}/${tags.1}/${tags.2}/${tags.3}/${now:%Y-%m-%d}_${now:%H-%M}
