# @package _global_

defaults:
  - base

metrics:
  recons_mse:
    _target_: ignite.metrics.MeanSquaredError
    output_transform:
      _target_: bin.extra.utils.create_output_transform
      pred_transform:
        _target_: bin.extra.utils.IndexSelector
        idx: [0, 0]

visualizations:
  reconstruction:
    _target_: bin.extra.visualization.ReconstructionViz

    recons_extractor:
      _target_: bin.extra.utils.IndexSelector
      idx: [0, 0]

  masks:
    _target_: bin.extra.visualization.SlotMaskViz

    mask_extractor:
      _target_: bin.extra.utils.IndexSelector
      idx: [1, 1]

    decoder_mask_extractor:
      _target_: bin.extra.utils.IndexSelector
      idx: [0, 1]
