# Format is:
#  <path-to-folder-and-path-in-config>:: <config-file>
#
#  When the path in the config folder and the config differ, we can use:
#  <path-to-folder>@<path-in-config>: <config-file>

defaults:
  - base_lgm
  - /loss@recons_loss: recons_bce
  - /loss@latent_loss: gaussian_kl
  - /training: default
  - _self_

_target_: src.model.autoencoder.VariationalAutoEncoder
