defaults:
  - dsprites
  - _self_

setting: supervised

_getter_params:
  target_transform:
    _target_: src.dataset.transforms.Compose
    transforms:
      - "${get_fn: src.dataset.dsprites.shape_prediction}"
