# @package _global_

defaults:
  - _self_  # override defaults
  - paths: default
  - hydra: default


task_name: analysis

tags: ["dev"]

seed: null

run_path: data/logs/composition_dsprites/runs/2023-01-15_15-45/

hydra:
  run:
    dir: ${run_path}/analysis
